### ISSUE TITLE
[Samsung S20 FE] wrong charge current displayed

### ISSUE THREAD

**Issue by Jakeler** [Ph03niX-X/CapacityInfo#35]
This is with a fast USB PD power supply connected and obviously too low:
![grafik](https://user-images.githubusercontent.com/13378765/200166244-645ac36b-9aa8-43cb-9fe7-61ed3dcba47f.png)
I guess the conversion factor is off by 1000, so 2-3 A would be expected, as it is pulling about 20 W from the port.
Also the remaining time prediction is wrong, system reports only 40 minutes, which is much closer than 820 h.

Samsung S20 FE with stock One UI 4.1, Android 12, October Security patch

**Comment by Ph03niX-X** [comment]
Hello! Please, Check Setting "Unit of Charge/Discharge Current"

**Comment by Jakeler** [comment]
Thank you! I did not see that, indeed switching from uA to mA makes it work perfectly. Great app!
