### ISSUE TITLE
bogus tips

### ISSUE THREAD

**Issue by ossilator** [Ph03niX-X/CapacityInfo#36]
the tips section of the readme suggests that you don't really know how battery chargers and chemistries actually work.

tip 2 is actually correct. but note that it's "undercool", not "overcool". i've seen this mistake in several other places as well.

tip 1 isn't wrong, but it's better to suggest 20%. but this is actually related to the next tips:

tips 3 and 4 are complete nonsense. "micro-cycles" don't affect battery life adversely, quite the opposite. the key is depth of discharge, which should be kept as shallow as possible. batteries live longest when kept between 40% and 80% of charge, which is why all the electric cars do it like that. the optimal charge level for long-term storage is 60%, but that's of course somewhat impractical, so 80% is a pragmatic limit. on the phone, an app like "battery charge limit" can be installed to keep it like that.

keeping the power adapter connected also doesn't cause noteworthy heating, unless the voltage converter that transforms the 5 volts input to match the ~3.7 volts battery voltage (which is used as the phone's "bus voltage") sucks completely. note that a phone contains at least half a dozen other voltage converters which are operating all the time (usually almost idling, like the connected input converter while not charging).
even to the degree it actually exists, such heating is extremely unlikely to outweigh the damage done by frequent deep cycling.

**Comment by ossilator** [comment]
so the "plan" is to keep spreading misinformation? that's an interesting philosophy.

**Comment by Ph03niX-X** [comment]
There is no misinformation

**Comment by ossilator** [comment]
yes, there is, and i explained what it is. you can take it from me as someone who actually works with such stuff, or do some research using reputable scientific/engineering sources.

you are also making recommendations that actively shorten battery life by encouraging deep cycling. it's much better to recommend leaving the phone on the charger at all times (ideally with a charge limiter).

**Comment by Ph03niX-X** [comment]
It makes no sense to limit the charge to 80%. It makes no sense to artificially lower the battery capacity by 20%. In laptops it might make sense if the laptop is constantly powered, but smartphones are never plugged in 24/7. Following my own advice, my smartphone battery has ~10% wear and tear in 21 months (33W). Technology does not stand still and I believe that the articles of Battery University have long been irrelevant

**Comment by ossilator** [comment]
yes, it does make sense, as otherwise the EV manufacturers wouldn't be doing it. it's a fundamental property of the chemistries that the ion migration causes stress on the electrodes, which gets bigger with the amplitude of each change. some electrodes take it better than others, but that doesn't change the principle.

in fact, lots of phones can be plugged in most of the time, because most people have access to a usb power source or a wireless charger most of the time. and they should take advantage of that.

it's true that none of this actually matters given the half-life of most phones, but by this logic you could just ignore the wear problem altogether.

the problem with any recommendation other than "keep it on the charger whenever possible" is that it's too complex for by far most users. this likely doesn't affect the user base of this app itself, but these people will also spread the information to more "normal" people.
