### ISSUE TITLE
Bug in A24

### ISSUE THREAD

**Issue by rsr123123** [Ph03niX-X/CapacityInfo#38]
Admin i wanted you to fix the bug that resets the screen time count on A24! It's normal on the J8 and I didn't stop the service on the A24!

**Comment by Ph03niX-X** [comment]
Hello! Thanks for reporting the bug! I'll see what I can do about it

**Comment by Ph03niX-X** [comment]
Hello! I need more information about your problem. How often does the screen time counter reset and under what circumstances?

**Comment by Ph03niX-X** [comment]
No answer for a long time

**Comment by Ph03niX-X** [comment]
No answer for a long time
