### ISSUE TITLE
Buy premium without Google

### ISSUE THREAD

**Issue by teodly** [Ph03niX-X/CapacityInfo#39]
Hello,

I'm using a phone with microG (unofficial, open source implementation of GSF) without Google Play services. I've installed the app from Aurora Store. I'd like to measure Wh and can pay for this feature. (btw I pay only for FOSS)

The problem is that the get premium button doesn't work, I suppose it depends on Play Store and 30% of my payment would go to Google which I'd like to avoid (they are rich enough already).

So please add an option of buying the premium through an independent channel (e.g. Patreon, itch.io, ...). It would be against the policy of the Play Store so this version of the app would need to be distributed as an .apk or in alternative store like F-Droid or https://accrescent.app/ - that would benefit privacy-aware users too.

BTW I need this feature ASAP to verify seller's claims about battery health and return the phone if they were false (I suspect they were). So I'd appreciate if you sold me the full version .apk directly, I can pay using PayPal or transfer to card.

**Comment by Ph03niX-X** [comment]
Hello! Im ready to give you apk file with activated Premium if you send me money. But there is a condition: don't distribute the apk file anywhere and don't send it to anyone
